export const PROPHET_DEFAULT_SETTINGS = Object.freeze({
  growth: 'linear',
  changepoint_prior_scale: 0.15,
  seasonality_prior_scale: 15.0,
  seasonality_mode: 'additive',
  daily_seasonality: false,
  weekly_seasonality: true,
  yearly_seasonality: true,
  forecast_periods: 365,
  floor_multiplier: 0.5,
  cap_multiplier: 1.5,
  enable_cap: true,
  enable_floor: true,
  custom_seasonality_enabled: false,
  custom_seasonality_name: '',
  custom_seasonality_period: 30.5,
  custom_seasonality_fourier_order: 3,
  n_changepoints: 25,
  changepoint_range: 0.8,
  interval_width: 0.80,
  holidays_prior_scale: 10.0,
  include_public_holidays: true,
  country: 'United Kingdom',
  holidays: [],
});
